### ISSUE TITLE
Permitir que seja utilizado quando não houver um arquivo de retorno

### ISSUE THREAD

**Issue by fabioviana** [jediproject/ng-jedi-download#2]
Caso seja usado para iniciar processos batch sem retorno de arquivo gerado dará crash no tratamento padrão atual.

**Comment by bsantosbhz** [comment]
Já estávamos com isso no radar. Só faltava abrir a issue!

**Comment by brunocs-cit** [comment]
Já estávamos com isso no radar. Só faltava abrir a issue!

**Comment by hsbrighenti** [comment]
Closede by commit 544dbc8f1634a155195d73ea9ed562b38df06105
